[workspace]
members = ["core_indexer"]
resolver = "2"

[workspace.package]
version = "0.12.0"
edition = "2021"
license = "MIT"
authors = ["CodeRadar Team"]
homepage = "https://opticswolf.github.io/coderadar/"
repository = "https://github.com/opticsWolf/coderadar"
documentation = "https://opticswolf.github.io/coderadar/"
